### ISSUE TITLE
NPM warning when installing "babel-preset-es2015-loose-native-modules"

### ISSUE THREAD

**Issue by hoangcuongvn** [easy-webpack/config-babel#3]
I see a warning when NPM installs this "babel-preset-es2015-loose-native-modules" package. It seems this babel preset is out-dated. Babel recommends using "babel-preset-es2015" with its options "loose", "modules".
https://github.com/babel/babel/blob/master/CHANGELOG.md#loose-and-modules-options-for-babel-preset-es2015-3331-3627

**Comment by niieani** [comment]
Indeed, I saw that `babel-preset-es2015` now added that feature. I'll tackle this at some point, on the other hand I'm also open for PRs since it's a trivial change.
